package com.endpointposture.job;

import com.endpointposture.endpoint.Endpoint;
import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * One unit of queued work against one endpoint.
 *
 * <p>Maps to the {@code posture_job} table ({@code V3__create_posture_jobs.sql}),
 * which replaces the Python project's flat-file queue. Workers claim rows
 * with {@code SELECT ... FOR UPDATE SKIP LOCKED} (see
 * {@link PostureJobRepository#findNextClaimable()}) so the same job is never
 * run twice.</p>
 */
@Entity
@Table(name = "posture_job")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PostureJob {

    /** Internal identifier, generated by the database. */
    @Id
    @GeneratedValue
    private UUID id;

    /**
     * The endpoint this job runs against. Lazy: it is only loaded when
     * touched, so it must be resolved while a transaction is still open
     * (see {@link JobService#claimNextJob()}).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "endpoint_id", nullable = false)
    private Endpoint endpoint;

    /** What kind of work to do. */
    @Enumerated(EnumType.STRING)
    @Column(name = "job_type", nullable = false)
    private JobType jobType;

    /** Where the job is in its lifecycle. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private JobStatus status;

    /** Higher values are claimed first; ties go to the oldest job. */
    @Column(nullable = false)
    private int priority;

    /** How many times a worker has started this job. */
    @Column(name = "attempt_count", nullable = false)
    private int attemptCount;

    /** Attempts allowed before the job is left in {@code FAILED}. */
    @Column(name = "max_attempts", nullable = false)
    private int maxAttempts;

    /** Reason for the most recent failure, if any. */
    @Column(name = "error_message")
    private String errorMessage;

    /** When the job was enqueued (UTC). */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** When a worker most recently started it (UTC). */
    @Column(name = "started_at")
    private Instant startedAt;

    /** When it reached {@code COMPLETE} or {@code FAILED} (UTC). */
    @Column(name = "completed_at")
    private Instant completedAt;

    /** Earliest time a retry may be claimed; {@code null} means eligible immediately. */
    @Column(name = "next_attempt_at")
    private Instant nextAttemptAt;

    /** Applies defaults just before the first insert. */
    @PrePersist
    void onCreate() {
        if (createdAt == null) createdAt = Instant.now();
        if (status == null) status = JobStatus.QUEUED;
        if (jobType == null) jobType = JobType.POSTURE_CHECK;
        if (maxAttempts == 0) maxAttempts = 3;
    }
}
