package com.endpointposture.security;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * A platform user who can log in to the dashboard/API.
 *
 * <p>Maps to the {@code app_user} table created by
 * {@code V1__create_users_and_roles.sql}. Passwords are stored only as
 * BCrypt hashes, never in plain text.</p>
 */
@Entity
@Table(name = "app_user")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /** Internal identifier, generated by the database. */
    @Id
    @GeneratedValue
    private UUID id;

    /** Login name. Unique across the table. */
    @Column(nullable = false, unique = true)
    private String username;

    /** BCrypt hash of the user's password. */
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    /** The user's role, stored as text (for example {@code ADMIN}). */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;

    /** Disabled users cannot log in. Defaults to {@code true} when built via the builder. */
    @Builder.Default
    @Column(nullable = false)
    private boolean enabled = true;

    /** When the account was created (UTC). Set automatically on first save. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Fills in {@link #createdAt} just before the first insert. */
    @PrePersist
    void prePersist() {
        if (createdAt == null) createdAt = Instant.now();
    }
}
