package com.endpointposture.endpoint;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * A device the platform knows about (a laptop, desktop or server seen via
 * Cisco ISE or a posture report).
 *
 * <p>Maps to the {@code endpoint} table ({@code V2__create_endpoints.sql}).
 * The MAC address is the real business key: ISE sessions and agent reports
 * both identify devices by MAC, so every ingestion path looks devices up by
 * MAC. The UUID exists only as a stable internal/API reference and as the
 * target of foreign keys from other tables.</p>
 *
 * <p>{@link #connected} is tracked independently of posture status: a device
 * can be connected with stale posture, or disconnected with a recent good
 * result.</p>
 */
@Entity
@Table(name = "endpoint")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Endpoint {

    /** Internal identifier, generated by the database. */
    @Id
    @GeneratedValue
    private UUID id;

    /** Normalized MAC address ({@code AA:BB:CC:DD:EE:FF}, uppercase). Unique. */
    @Column(name = "mac_address", nullable = false, unique = true)
    private String macAddress;

    /** Most recently observed IP address; also what the posture agent is dispatched against. */
    @Column(name = "ip_address")
    private String ipAddress;

    /** Reported hostname, if known. */
    private String hostname;

    /** Operating system name, if known. */
    @Column(name = "os_name")
    private String osName;

    /** Operating system version string, if known. */
    @Column(name = "os_version")
    private String osVersion;

    /** Whether the endpoint currently has an active ISE session. */
    @Column(nullable = false)
    private boolean connected;

    /** When the current session began; set when the endpoint goes from disconnected to connected. */
    @Column(name = "session_started_at")
    private Instant sessionStartedAt;

    /** When the endpoint last dropped off the network. */
    @Column(name = "last_disconnected_at")
    private Instant lastDisconnectedAt;

    /** Hardware manufacturer, reported by the posture agent. */
    private String manufacturer;

    /** Hardware model, reported by the posture agent. */
    private String model;

    /** Hardware serial number, reported by the posture agent. */
    @Column(name = "serial_number")
    private String serialNumber;

    /** First time this endpoint was ever seen (UTC). */
    @Column(name = "first_seen_at", nullable = false)
    private Instant firstSeenAt;

    /** Most recent time this endpoint was observed (UTC). */
    @Column(name = "last_seen_at", nullable = false)
    private Instant lastSeenAt;

    /** Row creation time (UTC). */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Row last-modified time (UTC). Refreshed automatically on every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Fills in the timestamp columns just before the first insert. */
    @PrePersist
    void onCreate() {
        Instant now = Instant.now();
        if (firstSeenAt == null) firstSeenAt = now;
        if (lastSeenAt == null) lastSeenAt = now;
        createdAt = now;
        updatedAt = now;
    }

    /** Refreshes {@link #updatedAt} just before every update. */
    @PreUpdate
    void onUpdate() {
        updatedAt = Instant.now();
    }
}
