package com.endpointposture.posture;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * One posture check of one endpoint at one point in time.
 *
 * <p>Maps to the {@code assessment} table ({@code V4__create_assessments.sql}).
 * The table is append-only: every check ever run adds a new row and existing
 * rows are never updated. That history is the "evidence" layer of the
 * platform's OBSERVATION, EVIDENCE, HUMAN REVIEW model. The individual
 * checks (firewall, ports, ...) live in {@link CheckResult} rows that point
 * back here.</p>
 */
@Entity
@Table(name = "assessment")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Assessment {

    /** Internal identifier, generated by the database. */
    @Id
    @GeneratedValue
    private UUID id;

    // Plain UUID columns, not @ManyToOne object references - same
    // pattern already used for endpoint_id on PostureJob. Keeps writes
    // simple (no cascade/lazy-loading surprises) and matches how the
    // rest of this codebase treats FK columns.

    /** The endpoint that was assessed. */
    @Column(name = "endpoint_id", nullable = false)
    private UUID endpointId;

    /** The queue job that triggered this assessment; {@code null} if that job was later purged. */
    @Column(name = "job_id")
    private UUID jobId; // nullable - ON DELETE SET NULL in the schema

    /** Overall result across all checks. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AssessmentStatus status;

    /** Short human-readable summary, for example which checks failed or why the run errored. */
    private String detail;

    /** When collection began (as reported by the agent). */
    @Column(name = "started_at", nullable = false)
    private Instant startedAt;

    /** When the assessment was finished and recorded. */
    @Column(name = "completed_at")
    private Instant completedAt;

    /** Row creation time (UTC). */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Fills in {@link #createdAt} just before the first insert. */
    @PrePersist
    void onCreate() {
        if (createdAt == null) createdAt = Instant.now();
    }
}
