package com.endpointposture.posture;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * The result of one individual check (firewall, open ports, applications, ...)
 * within an {@link Assessment}.
 *
 * <p>Maps to the {@code check_result} table. Like assessments, rows are
 * append-only.</p>
 */
@Entity
@Table(name = "check_result")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CheckResult {

    /** Internal identifier, generated by the database. */
    @Id
    @GeneratedValue
    private UUID id;

    /** The assessment this check belongs to. */
    @Column(name = "assessment_id", nullable = false)
    private UUID assessmentId;

    // Kept as a plain String rather than a Java enum deliberately -
    // check_type is meant to stay open-ended (FIREWALL, OPEN_PORTS,
    // APPLICATIONS, and whatever gets added later) without a Java
    // enum + migration every time a new evaluator is added.

    /** Kind of check, for example {@code FIREWALL}, {@code OPEN_PORTS}, {@code APPLICATIONS}. */
    @Column(name = "check_type", nullable = false)
    private String checkType;

    /** Result of this one check. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AssessmentStatus status;

    // Native Hibernate 6 JSONB mapping - no extra dependency needed
    // (Hibernate 6.6.x, which this project is already on, has
    // @JdbcTypeCode(SqlTypes.JSON) built in).

    /** Raw facts behind the result, stored as JSONB so its shape can vary per check type. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private Map<String, Object> details;

    /** Row creation time (UTC). */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Fills in {@link #createdAt} just before the first insert. */
    @PrePersist
    void onCreate() {
        if (createdAt == null) createdAt = Instant.now();
    }
}
